---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: myapp
  name: myapp
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: http
      nodePort: 30880
  selector:
    app: myapp
  type: NodePort
